name: flutter_bleu
description: Offline Flutter static & architecture analyzer
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  args: ^2.4.0
  path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0

executables:
  flutter_bleu: